version: '3.8'
services:
  jaeger:
    hostname: jaeger
    image: jaegertracing/all-in-one:latest
    ports:
      - '16686:16686'
      - '14250'
  collector:
    hostname: otlp
    image: otel/opentelemetry-collector:latest
    command: ['--config=/etc/otel-collector-config.yaml']
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
  nginx:
    hostname: nginx
    image: nginx-otel
    volumes:
      - ./opentelemetry_module.conf:/etc/nginx/conf.d/opentelemetry_module.conf
    ports:
      - 8081:80
