receivers:
  otlp:
    protocols:
      grpc:
      http:
exporters:
  otlp:
    endpoint: 0.0.0.0:14250
    tls:
      insecure: true
service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [otlp]
